# Generated by Django 5.1.1 on 2024-11-08 06:10

import api.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=api.users.models.user_image_location, validators=[django.core.validators.FileExtensionValidator(['ico', 'jpg', 'svg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'tiff', 'ttf', 'eot', 'woff', 'woff2'])], verbose_name='Images'),
        ),
    ]
